#!/usr/bin/env bash
# pr-description.sh — generate PR description body from template
#
# Usage:
#   pr-description.sh
#
# Reads task fields from environment variables:
#   TASK_ID            — task ID from plan YAML
#   TASK_TITLE         — task title from plan YAML
#   TASK_DESCRIPTION   — task description from plan YAML
#   EPIC_TITLE         — epic title from plan YAML
#   BRANCH             — feature branch name
#   PLAN_PATH          — path to the plan YAML file
#   WORKTREE           — worktree path
#
# Outputs the rendered PR body to stdout.

set -euo pipefail

_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${_SCRIPT_DIR}/../../../scripts/config.sh"

# Default built-in template
_DEFAULT_TEMPLATE='## What
{task_description}

## Why
Part of epic: {epic_title}

## Task
- ID: {task_id}
- Branch: {branch}
- Plan: {plan_path}

---
*Generated by [agent-workflow](https://github.com/evanisnor/agent-workflow)*'

# Select template
_TEMPLATE=""
if [[ -n "${PR_TEMPLATE_PATH:-}" ]] && [[ -f "${PR_TEMPLATE_PATH}" ]]; then
  _TEMPLATE="$(cat "${PR_TEMPLATE_PATH}")"
else
  _TEMPLATE="${_DEFAULT_TEMPLATE}"
fi

# Interpolate variables — replace each {variable} with its env value
_render() {
  local tmpl="$1"
  tmpl="${tmpl//\{task_id\}/${TASK_ID:-}}"
  tmpl="${tmpl//\{task_title\}/${TASK_TITLE:-}}"
  tmpl="${tmpl//\{task_description\}/${TASK_DESCRIPTION:-}}"
  tmpl="${tmpl//\{epic_title\}/${EPIC_TITLE:-}}"
  tmpl="${tmpl//\{branch\}/${BRANCH:-}}"
  tmpl="${tmpl//\{plan_path\}/${PLAN_PATH:-}}"
  tmpl="${tmpl//\{worktree\}/${WORKTREE:-}}"
  printf '%s' "${tmpl}"
}

_render "${_TEMPLATE}"
