#!/usr/bin/env bash
# pr-description.sh — generate PR description body from template
#
# Usage:
#   pr-description.sh
#
# Reads task fields from environment variables:
#   TASK_ID            — task ID from plan YAML
#   TASK_TITLE         — task title from plan YAML
#   TASK_DESCRIPTION   — formatted bulleted list of what was implemented
#   TASK_CONTEXT       — 1-2 sentences explaining why this task exists
#   EPIC_TITLE         — epic title from plan YAML
#   PLAN_PATH          — path to the plan YAML file (used only in custom templates)
#   WORKTREE           — worktree path (used only in custom templates)
#
# Outputs the rendered PR body to stdout.

set -euo pipefail

_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${_SCRIPT_DIR}/../../../scripts/config.sh"

if [[ -n "${PR_DESCRIPTION_SKILL:-}" ]]; then
  echo "Error: pr.description_skill is configured — invoke that skill instead of pr-description.sh." >&2
  exit 1
fi

# Default built-in template
_DEFAULT_TEMPLATE='## What
{task_description}

## Why
{task_context}

## Task
`{task_id}` — {epic_title}

---
*Generated by [agent-workflow](https://github.com/evanisnor/agent-workflow)*'

# Select template
_TEMPLATE=""
if [[ -n "${PR_TEMPLATE_PATH:-}" ]] && [[ -f "${PR_TEMPLATE_PATH}" ]]; then
  _TEMPLATE="$(cat "${PR_TEMPLATE_PATH}")"
else
  _TEMPLATE="${_DEFAULT_TEMPLATE}"
fi

# Interpolate variables — replace each {variable} with its env value
_render() {
  local tmpl="$1"
  tmpl="${tmpl//\{task_id\}/${TASK_ID:-}}"
  tmpl="${tmpl//\{task_title\}/${TASK_TITLE:-}}"
  tmpl="${tmpl//\{task_description\}/${TASK_DESCRIPTION:-}}"
  tmpl="${tmpl//\{task_context\}/${TASK_CONTEXT:-}}"
  tmpl="${tmpl//\{epic_title\}/${EPIC_TITLE:-}}"
  tmpl="${tmpl//\{branch\}/${BRANCH:-}}"
  tmpl="${tmpl//\{plan_path\}/${PLAN_PATH:-}}"
  tmpl="${tmpl//\{worktree\}/${WORKTREE:-}}"
  printf '%s' "${tmpl}"
}

_render "${_TEMPLATE}"
